#!/usr/bin/env python3
import os
import re
import subprocess

def integrate_peano_axioms_core():
    filepath = 'week1.html'
    if not os.path.exists(filepath):
        print(f"Error: {filepath} not found.")
        return

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Core prose markup without card wrappers
    core_markup = r'''            <!-- CORE FOUNDATION: PEANO AXIOMS & NATURAL NUMBERS -->
            <div class="content-block" style="margin-top: 1.5rem; margin-bottom: 2rem;">
                <h3 style="color: #0f172a; margin-bottom: 0.75rem;">Axiomatic Foundations: Peano's Axioms for $\mathbb{N}$</h3>
                <p style="font-size: 1rem; line-height: 1.7; color: #1e293b;">
                    Before constructing algebraic fields or real analysis metrics, the natural numbers $\mathbb{N}$ must be rigorously defined. Rather than taking counting for granted, the natural numbers are formally characterized by <strong>Peano's axioms</strong>, which specify a base element $0 \in \mathbb{N}$ and an injective successor function $S: \mathbb{N} \to \mathbb{N}$ (intuitively representing $S(n) = n + 1$).
                </p>

                <ol style="font-size: 0.97rem; line-height: 1.7; color: #1e293b; margin: 1rem 0 1.25rem 1.5rem;">
                    <li style="margin-bottom: 0.65rem;">
                        <strong>Existence of Zero (Base Element):</strong> $0 \in \mathbb{N}$. Ensures that the set $\mathbb{N}$ is non-empty and provides a foundational root.
                    </li>
                    <li style="margin-bottom: 0.65rem;">
                        <strong>Closure Under Successor:</strong> $\forall n \in \mathbb{N}, \; S(n) \in \mathbb{N}$. Every natural number has an unambiguously defined successor in $\mathbb{N}$.
                    </li>
                    <li style="margin-bottom: 0.65rem;">
                        <strong>Injectivity of Successor (No Branching / Merging):</strong> $\forall m, n \in \mathbb{N}, \; S(m) = S(n) \implies m = n$. Distinct numbers cannot have identical successors. In graph-theoretic terms, every node has an in-degree of at most 1, preventing distinct paths from collapsing into one another.
                    </li>
                    <li style="margin-bottom: 0.65rem;">
                        <strong>Non-Surjectivity onto Zero (No Predecessor / No Cycles):</strong> $\forall n \in \mathbb{N}, \; S(n) \ne 0$. Zero is not the successor of any natural number ($0 \notin \text{range}(S)$). This prevents cyclic wrap-around paths (such as finite clock arithmetic $\mathbb{Z}/n\mathbb{Z}$) and establishes $0$ as the strict starting origin.
                    </li>
                    <li style="margin-bottom: 0.65rem;">
                        <strong>Axiom of Induction (Connectedness &amp; Minimality):</strong> Let $K \subseteq \mathbb{N}$. If $0 \in K$ and $[\forall n \in \mathbb{N}, \; (n \in K \implies S(n) \in K)]$, then $K = \mathbb{N}$.<br>
                        While axioms 1–4 prevent loops and branching, they still permit disconnected "ghost chains" (isolated infinite linear components or cycles unlinked to $0$). The induction axiom serves as a minimality condition, guaranteeing that $\mathbb{N}$ contains <em>only</em> those elements generated by applying $S$ finitely many times starting from $0$.
                    </li>
                </ol>

                <p style="font-size: 1rem; line-height: 1.7; color: #1e293b;">
                    From this minimalist framework, all arithmetic operations are defined recursively without circularity:
                </p>
                <ul style="font-size: 0.95rem; line-height: 1.7; color: #1e293b; margin: 0.5rem 0 1rem 1.5rem;">
                    <li><strong>Addition ($+$):</strong> Defined inductively by $n + 0 = n$ and $n + S(m) = S(n + m)$.</li>
                    <li><strong>Multiplication ($\cdot$):</strong> Defined inductively by $n \cdot 0 = 0$ and $n \cdot S(m) = (n \cdot m) + n$.</li>
                </ul>
                <p style="font-size: 0.95rem; line-height: 1.7; color: #334155;">
                    The standard algebraic laws—associativity, commutativity, and distributivity—all follow directly as formal theorems proved via mathematical induction.
                </p>
            </div>'''

    # Pattern to match previously inserted card or inline box
    card_pattern = r'<div style="font-weight: 600; font-size: 1.05rem; color: #1e293b; margin-top: 1.25rem;">Axiomatic Foundations: Peano\'s Axioms for \$\\mathbb\{N\}\$</div>[\s\S]*?mathematical induction\.\s*</div>'

    if re.search(card_pattern, content):
        content = re.sub(card_pattern, core_markup, content, count=1)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print("Replaced card-based Peano axioms with core content flow in week1.html.")
        return

    # If the card markup isn't found, inject directly before Section 2 (Set Operations)
    target = r'2. Set Operations'
    match = re.search(r'(<div[^>]*>.*?2\.\s*Set Operations.*?</div>)', content)
    if match:
        content = content[:match.start()] + core_markup + '\n\n' + content[match.start():]
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print("Integrated Peano axioms into main body preceding Set Operations in week1.html.")
    else:
        print("Could not identify insertion anchor in week1.html.")

def execute_git_sync():
    commit_message = (
        "Refactor Peano axioms from card container to core body content\n\n"
        "Integrated Peano axioms directly into the primary document flow of\n"
        "week1.html, establishing the natural numbers foundation as core text\n"
        "rather than an isolated card component."
    )
    commands = [
        ['git', 'add', 'week1.html', 'update.py'],
        ['git', 'commit', '-m', commit_message],
        ['git', 'push', 'origin', 'main']
    ]
    for cmd in commands:
        result = subprocess.run(cmd, capture_output=True, text=True)
        print(f"> {' '.join(cmd)}\n{result.stdout}{result.stderr}")

if __name__ == '__main__':
    integrate_peano_axioms_core()
    execute_git_sync()
